export const actionTypes={
    FETCH_PRODUCTS:"FETCH_PRODUCTS",
    DELETE_PRODUCT:"DELETE_PRODUCT",
    SET_PRODUCTS:"SET_PRODUCTS",
    FETCH_CART:"FETCH_CART",
    DELETE_CART:"DELETE_CART",
    FETCH_PRODUCTS_BY_CATEGORY:"FETCH_PRODUCTS_BY_CATEGORY"
}